export { HitPoints } from "./HitPoints";
export { ContactDamage } from "./ContactDamage";
export { Fragile } from "./Fragile";
export { DestroyOnZeroHP } from "./DestroyOnZeroHP";
export { CreatePrefabsOnDestroyed } from "./CreatePrefabsOnDestroyed";
export { ExamplePlayer } from "./ExamplePlayer";
export { ShapeStateController as ShapeStateController } from "./ShapeStateController";
export { Collectible as Collectable } from "./Collectible";
export {RotateMotion} from "./RotateMotion";
export {ScoreItem} from "./ScoreItem";
export {GuideBody} from "./GuideBody";
export {ShapeStateAnimator} from "./ShapeStateAnimator";
export {AvatarBase} from "./AvatarBase";
export {PlatformerAvatar} from "./PlatformerAvatar";
export {CameraTarget} from "./CameraTarget";